services:
  xray:
    image: ghcr.io/xtls/xray-core:26.7.28
    container_name: xray-mitm
    restart: always
    ports:
      - "40443:40443"
    volumes:
      - ./config.json:/etc/xray/config.json:ro
    command: [ "run", "-c", "/etc/xray/config.json" ]
