services:
  xray:
    image: ghcr.io/xtls/xray-core:26.7.28
    container_name: xray-fragment-mitm
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./config.json:/etc/xray/config.json:ro
    command: [ "run", "-c", "/etc/xray/config.json" ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
